---
title: "Percent Cover of Benthic Functional Groups"
author: "JJH"
editor: visual
---

```{r, include = FALSE}
require(tidyverse)
require(plyr)
require(betareg)
require(lmtest)
require(glmmTMB)
require(boot)
require(emmeans)
require(brms)
require(mvtnorm)
require(nlme)
require(rstan)
require(VGAM)
require(Rmisc)
require(car)
```

```{r, include = FALSE}
rpn_2016_main2 <- read.csv("rpn_2016_main2.csv") %>%
  as_tibble() %>%
  mutate_at(vars(location, depth, group), factor)
```

```{r}
rpn_2016_main2
```

<div style = "margin-bottom:50px;">
```{r}
rpn_2016_main.plob <- 
  rpn_2016_main2 %>%
  filter(group == "plob") %>%
  mutate(transect = case_when(
    startsWith(photo, "t1_") ~ "transect1",
    startsWith(photo, "t2_") ~ "transect2",
    startsWith(photo, "t3_") ~ "transect3",
    startsWith(photo, "t4_") ~ "transect4"
  )
) %>%
  mutate_at(vars(location, group, transect), factor)
```
</div>

```{r, include = TRUE}
rpn_2016_main.plob
```

First use a two-way ANOVA on the raw data, percent cover given by the proportional value.
Run a two-way ANOVA with and without interaction.

```{r}
plob.lm1 <- lm(cover ~ location + depth, data = rpn_2016_main.plob)
plob.lm2 <- lm(cover ~ location * depth, data = rpn_2016_main.plob)
```

```{r}
par(mfrow = c(2, 2))
plot(plob.lm1)
```

```{r}
summary(plob.lm1)
```

```{r}
Anova(plob.lm1, type = "III")
```

```{r}
par(mfrow = c(2, 2))
plot(plob.lm2)
```

```{r}
summary(plob.lm2)
```

```{r}
Anova(plob.lm2, type = "III")
```

**Two-Way ANOVA -- Logit transformed**

<div style = "margin-bottom:50px;">
```{r}
plob.lm.logit <- lm(logit(cover) ~ location * depth, data = rpn_2016_main.plob)
```
</div>

<div style = "margin-bottom:50px;">
```{r}
par(mfrow = c(2, 2))
plot(plob.lm.logit)
```
</div>

<div style = "margin-bottom:50px;">
```{r}
summary(plob.lm.logit)
```
</div>

<div style = "margin-bottom:50px;">
```{r}
Anova(plob.lm.logit, type = "III")
```
</div>

**Random Effects**

<div style = "margin-bottom:50px;">
```{r, eval = T, collapse = T, message = FALSE}
plob_2016_aov.1 <- aov(cover ~ location * depth + Error(transect), data = rpn_2016_main.plob)
```
</div>

<div style = "margin-bottom:50px;">
```{r}
summary(plob_2016_aov.1)
```
</div>

<div style = "margin-bottom:50px;">
Using the library `nlme` for mixed effects modeling.

```{r}
plob_2016_lme.1 <- lme(cover ~ location * depth, random = ~ 1 | transect, data = rpn_2016_main.plob)
```
</div>

<div style = "margin-bottom:50px;">
```{r}
summary(plob_2016_lme.1)
```
</div>

<div style = "margin-bottom:50px;">
```{r}
Anova(plob_2016_lme.1, type = "III")
```
</div>















